//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { schema as $schema, type SchemaType as $Schema } from "./schema";
import type { ModelResult as $ModelResult, TypeDefResult as $TypeDefResult } from "@zenstackhq/orm";
export type User = $ModelResult<$Schema, "User">;
export type Session = $ModelResult<$Schema, "Session">;
export type Account = $ModelResult<$Schema, "Account">;
export type Verification = $ModelResult<$Schema, "Verification">;
export type Organization = $ModelResult<$Schema, "Organization">;
export type OrganizationRole = $ModelResult<$Schema, "OrganizationRole">;
export type Member = $ModelResult<$Schema, "Member">;
export type Invitation = $ModelResult<$Schema, "Invitation">;
export type TwoFactor = $ModelResult<$Schema, "TwoFactor">;
export type Person = $ModelResult<$Schema, "Person">;
export type UserParent = $ModelResult<$Schema, "UserParent">;
export type Year = $ModelResult<$Schema, "Year">;
export type Period = $ModelResult<$Schema, "Period">;
export type LearningUnit = $ModelResult<$Schema, "LearningUnit">;
export type LearningGroup = $ModelResult<$Schema, "LearningGroup">;
export type Student = $ModelResult<$Schema, "Student">;
export type StudentGroup = $ModelResult<$Schema, "StudentGroup">;
export type CourseEnrollment = $ModelResult<$Schema, "CourseEnrollment">;
export type Employee = $ModelResult<$Schema, "Employee">;
export type EmployeeLearningUnit = $ModelResult<$Schema, "EmployeeLearningUnit">;
export type AuditLog = $ModelResult<$Schema, "AuditLog">;
export type UserDevice = $ModelResult<$Schema, "UserDevice">;
export type Post = $ModelResult<$Schema, "Post">;
export type Notification = $ModelResult<$Schema, "Notification">;
export type OrgBase = $TypeDefResult<$Schema, "OrgBase">;
export const Gender = $schema.enums.Gender.values;
export type Gender = (typeof Gender)[keyof typeof Gender];
export const ParentRelationship = $schema.enums.ParentRelationship.values;
export type ParentRelationship = (typeof ParentRelationship)[keyof typeof ParentRelationship];
export const StudentStatus = $schema.enums.StudentStatus.values;
export type StudentStatus = (typeof StudentStatus)[keyof typeof StudentStatus];
export const StudentGroupStatus = $schema.enums.StudentGroupStatus.values;
export type StudentGroupStatus = (typeof StudentGroupStatus)[keyof typeof StudentGroupStatus];
export const CourseEnrollmentStatus = $schema.enums.CourseEnrollmentStatus.values;
export type CourseEnrollmentStatus = (typeof CourseEnrollmentStatus)[keyof typeof CourseEnrollmentStatus];
export const PostStatus = $schema.enums.PostStatus.values;
export type PostStatus = (typeof PostStatus)[keyof typeof PostStatus];
export const NotificationChannel = $schema.enums.NotificationChannel.values;
export type NotificationChannel = (typeof NotificationChannel)[keyof typeof NotificationChannel];
